from __future__ import annotations

import subprocess
import time

import pyperclip

try:
    from AppKit import NSPasteboard, NSPasteboardTypeString
except Exception:  # pragma: no cover - AppKit is only available on macOS with PyObjC.
    NSPasteboard = None
    NSPasteboardTypeString = None


TRANSIENT_PASTEBOARD_TYPES = (
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "org.nspasteboard.ConcealedType",
)
RESTORED_PASTEBOARD_TYPES = (
    "org.nspasteboard.TransientType",
    "org.nspasteboard.RestoredType",
)


def insert_text(
    text: str,
    method: str = "auto",
    restore_clipboard: bool = True,
    mark_transient: bool = True,
) -> None:
    if method in ("auto", "direct"):
        try:
            _insert_with_system_events(text)
            return
        except subprocess.SubprocessError:
            if method == "direct":
                raise
    _insert_with_clipboard(text, restore_clipboard=restore_clipboard, mark_transient=mark_transient)


def _insert_with_system_events(text: str) -> None:
    script = """
    on run argv
      tell application "System Events"
        keystroke (item 1 of argv)
      end tell
    end run
    """
    _run_osascript(script, text)


def _insert_with_clipboard(text: str, restore_clipboard: bool, mark_transient: bool) -> None:
    previous = None
    if restore_clipboard:
        try:
            previous = pyperclip.paste()
        except pyperclip.PyperclipException:
            previous = None
    _copy_to_pasteboard(text, mark_transient=mark_transient, restored=False)
    script = 'tell application "System Events" to keystroke "v" using command down'
    _run_osascript(script)
    if restore_clipboard and previous is not None:
        time.sleep(0.2)
        _copy_to_pasteboard(previous, mark_transient=mark_transient, restored=True)


def _copy_to_pasteboard(text: str, mark_transient: bool, restored: bool) -> None:
    if mark_transient and _copy_to_macos_pasteboard(text, restored=restored):
        return
    pyperclip.copy(text)


def _copy_to_macos_pasteboard(text: str, restored: bool) -> bool:
    if NSPasteboard is None or NSPasteboardTypeString is None:
        return False
    pasteboard = NSPasteboard.generalPasteboard()
    pasteboard.clearContents()
    if not pasteboard.setString_forType_(text, NSPasteboardTypeString):
        return False
    marker_types = RESTORED_PASTEBOARD_TYPES if restored else TRANSIENT_PASTEBOARD_TYPES
    for pasteboard_type in marker_types:
        pasteboard.setString_forType_("", pasteboard_type)
    return True


def _run_osascript(script: str, *args: str) -> None:
    subprocess.run(
        ["osascript", "-e", script, *args],
        check=True,
        timeout=5,
        capture_output=True,
        text=True,
    )
